"""add direction column to user_settings

Revision ID: 6eeec23048e8
Revises: fa42c3390aa1
Create Date: 2025-09-19 10:57:22.438852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eeec23048e8'
down_revision: Union[str, Sequence[str], None] = 'fa42c3390aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('direction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'direction')
    # ### end Alembic commands ###
